sudo: required
dist: trusty
language: generic

services:
- docker

env:
  global:
    KITCHEN_LOCAL_YAML: .kitchen.travis.yml

install:
- curl https://chef.io/chef/install.sh | sudo bash -s -- -P chefdk
- chef gem install kitchen-docker test-kitchen appbundle-updater
- sudo chef exec appbundle-updater chefdk test-kitchen v1.6.0

script:
- docker version
- kitchen --version
- kitchen test -d always
