sudo: required
dist: trusty
language: generic

services:
- docker

env:
  global:
    KITCHEN_LOCAL_YAML: .kitchen.travis.yml

install:
- curl https://chef.io/chef/install.sh | sudo bash -s -- -P chefdk
- chef gem install test-kitchen

script: kitchen test -d always
